image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - x64

clone_depth: 1

configuration:
  - Release
  - Debug

cache: C:\Tools\vcpkg\installed

build:
  parallel: true

before_build:
  - C:\Tools\vcpkg\vcpkg install assimp:x64-windows
  - C:\Tools\vcpkg\vcpkg install glfw3:x64-windows
  - C:\Tools\vcpkg\vcpkg install glm:x64-windows

build_script:
  - mkdir build || exit 1
  - pushd build && ( cmake -A x64 -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake .. & popd ) || exit 1
  - cmake --build build --config %CONFIGURATION% || exit 1
