language: cpp

os:
  - linux
  - osx
dist: focal
osx_image: xcode12

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE="Release"
  - BUILD_TYPE="Debug"

jobs:
  exclude:
    - os: osx
      compiler: gcc

git:
  depth: 1

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libassimp-dev libglfw3-dev; fi

script:
  - mkdir build || exit 1
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then generator='Xcode'; else generator='Ninja'; fi
  - pushd build && { cmake -DCMAKE_CXX_FLAGS="-Wall" \
                           -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
                           -G "$generator" ..; popd; } || exit 1
  - cmake --build build || exit 1
